pip install flask
pip install pymongo
pip install pandas
pip install dnspython
pip install cryptography
pip install validate-docbr
pip install email-validator
pip install dnspython
pip install pytest
